{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recipe-frontend-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.pdb.frontend.minAvailable }}
  selector:
    matchLabels:
      app: recipe-frontend
{{- end }}