apiVersion: v1
kind: Service
metadata:
  name: recipe-frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: recipe-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: recipe-frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}