{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recipe-backend-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.pdb.backend.minAvailable }}
  selector:
    matchLabels:
      app: recipe-backend
{{- end }}