apiVersion: v1
kind: Service
metadata:
  name: recipe-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: recipe-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
  selector:
    app: recipe-backend